version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      # node_modules papkasini konteyner ichida saqlash
      - /app/node_modules